### ISSUE TITLE
No guard about invalid format (No check about unmatched pattern)

### ISSUE THREAD

**Issue by tagomoris** [naritta/mruby-fast-strptime#1]
This library provides no protection about unmatched pattern - so we will get wrong result if we wrote invalid time pattern (and it's very hard to find the root cause).

With wrong time format (`N` instead of `%N` here), `naruse/strptime` reports unmatched pattern:
```
$ ruby -rstrptime -e 'p Strptime.new("%Y-%m-%d %H:%M:%S.N %z").exec("2017-10-06 13:15:30.0 +00:00")'
-e:1:in `exec': string doesn't match (ArgumentError)
	from -e:1:in `<main>'
```

But this library returns a surprising time value:
```
$ mruby -e 'p Strptime.new("%Y-%m-%d %H:%M:%S.N %z").exec("2017-10-06 13:15:30.0 +00:00")'
Sun Mar 15 17:53:20 4444257
```

**Comment by tagomoris** [comment]
@naritta ping?

**Comment by naritta** [comment]
I fixed here.
https://github.com/naritta/mruby-fast-strptime/commit/107b53ee1c859c3cf83a8f6fb3f596b52cc626e1
https://github.com/naritta/mruby-fast-strptime/commit/d08fdd2f546bd3429e0641566e75f37c30799c7d

**Comment by tagomoris** [comment]
@naritta Are there any special reason to raise RuntimeError instead of ArgumentError?

**Comment by naritta** [comment]
I fixed here.
https://github.com/naritta/mruby-fast-strptime/commit/de378d35eb02b774aab66cc23335597778daf311

**Comment by tagomoris** [comment]
That works fine for me. Thanks!
